### ISSUE TITLE
Roadmap 2019

### ISSUE THREAD

**Issue by WoodNeck** [naver/egjs-flicking#257]
- [ ] Perfomance enhancement
  - Render performance improvement with infinite option.
- [ ] Enhance usability
  - Add range or visible option for `getStatus`
  - Add `fill()` method for needPanel event
  - option to disable iOS's edge swipe
  - `moveToClicked` option to move camera to clicked panel
- [ ] UI Customizing
  - `virtualTranslate` option which makes panel's `left` or camera's `transform` CSS not to be applied.
  - `interrupt` option, which can disable user interruption while animating.
  - Add some new move types(strict, agile, ...)
- [ ] Support key-based panels
- [ ] Support dynamic option change
- [ ] Support data attribute for panels (index, anchor ...)
- [ ] Support nested flicking
  - `nested` option for multiple Flicking instance
- [ ] Plugins
  - Add pagination & arrow plugin
- [ ] Frameworks
  - Support Preact
- [ ] Refactoring
  - Refactor into MoveType-based interface

**Comment by masihurmaruf** [comment]
Is there any plan to support external click to move to panel. For example.

say there is 5 panel. I am on panel 2. Click a button, jump to panel 4. click another button, jump to panel 1 etc.

In any case awesome project and thanks for the amazing work.

**Comment by WoodNeck** [comment]
Hello, @masihurmaruf :)
That can be easily done with panel's methods.
```js
flicking.getCurrentPanel().prev().prev().focus(duration);
```

Here's an example:
https://codepen.io/woodneck/pen/YzwbWWa

**Comment by vasinl124** [comment]
Is there any plan to scroll horizontally on the desktop without click and drag? 
something like this - https://crello.com/home/

**Comment by WoodNeck** [comment]
Hello, @vasinl124 
I think it can be done when "Move by n px" method for Freescroll move type is added :)

**Comment by vasinl124** [comment]
> Hello, @vasinl124
> I think it can be done when "Move by n px" method for Freescroll move type is added :)

Thanks, do you know when it will be added?

**Comment by WoodNeck** [comment]
@vasinl124 
It's already there at the moment, but the interface is just not public.
We're planning to make a more clear interface for those functions next version.
Here's a sample demo for you: https://codepen.io/woodneck/pen/MWyeXjB

**Comment by gamtiq** [comment]
First of all I would like to thank for the excellent tool!

> Add pagination & arrow plugin

IMHO pagination and arrow navigation are very useful features (especially when they are flexible and customizable) that `Flicking` are lacking.
So I vote to prioritize creation of the corresponding plugins.

Another features that should be handled first (in priority descending):
* Navigation/scrolling by mouse wheel (_absent in roadmap_ - #380)
* "Move by n px" method for Freescroll move type
* Add indicator method/getter for checking whether Flicking is at boundary
* Support dynamic option change
* Navigation/scrolling by keyboard _(absent in roadmap)_
* Support data attribute for panels (index, anchor ...)

**Comment by WoodNeck** [comment]
@gamtiq
Thanks for the suggestion! I totally agree with your opinion.
I was kinda busy working for the [@egjs/view3d](https://github.com/naver/egjs-view3d) this year.
I'll do my best so I can add that features as soon as possible :)

**Comment by acroyear** [comment]
> * Navigation/scrolling by keyboard _(absent in roadmap)_

This is a feature I would need as well. The Options show how easy it is to recreate, say, the header section of Disney+'s home screen, but without keyboard navigation, it isn't very useful for a TV application where the remote control 4-direction (and enter key) are the only ways to move around.

**Comment by WoodNeck** [comment]
@acroyear 
Thanks for the suggestion! I'll add that on the roadmap :)

**Comment by WoodNeck** [comment]
@BenjaminBrodwolf
Looks like I didn't include an automatic update for it.
I'll update that, but until then you can call `resize` after you update those values.
Like, in Angular you can call `flicking.resize()` in the `ngAfterContentChecked` (see [Using the methods](https://naver.github.io/egjs-flicking/docs/using-the-methods))

**Comment by netzpixel** [comment]
is this fixed by now? I'm using the vue2 variant and give in the panelsPerView as a prop but when it's value changes, the slider doesn't update.
